# Generated by Django 2.1.4 on 2018-12-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
                ('addHealth', models.PositiveIntegerField(default=0)),
                ('addAttack', models.PositiveIntegerField(default=0)),
                ('addDefend', models.PositiveIntegerField(default=0)),
                ('addSpeed', models.PositiveIntegerField(default=0)),
                ('addDodgeRate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('health', models.PositiveIntegerField(default=0)),
                ('attack', models.PositiveIntegerField(default=0)),
                ('defend', models.PositiveIntegerField(default=0)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('dodgeRate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('position_picture', models.ImageField(default=None, upload_to='./position/')),
                ('description', models.TextField(default='到此一游', null=True)),
                ('itemLinked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wechatId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('checkInPositions', models.ManyToManyField(through='model.CheckInRecord', to='model.Position')),
                ('likes', models.ManyToManyField(through='model.LikeRecord', to='model.User')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='model.User'),
        ),
        migrations.AddField(
            model_name='likerecord',
            name='userFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='likerecord',
            name='userTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beingLikeds', to='model.User'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Position'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
    ]
