# Generated by Django 2.1.4 on 2018-12-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20181214_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='appearanceID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
