# Generated by Django 2.1.4 on 2018-12-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_pet_appearanceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='appearanceID',
            new_name='appearanceId',
        ),
    ]
