# Generated by Django 2.1.4 on 2018-12-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20181218_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastLatitude',
            field=models.DecimalField(decimal_places=15, default=116.3, max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastLongitude',
            field=models.DecimalField(decimal_places=15, default=40.0, max_digits=20),
        ),
    ]
