# Generated by Django 2.1.4 on 2018-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20181221_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalLikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
