# Generated by Django 2.1.4 on 2018-12-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_user_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.TextField(default='http://pic.51yuansu.com/pic3/cover/01/69/80/595f67bf2026f_610.jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
