# Generated by Django 2.1.4 on 2019-01-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20181228_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User')),
                ('userTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beingBattleds', to='model.User')),
            ],
        ),
    ]
