# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('petname', models.CharField(max_length=32)),
                ('level', models.PositiveIntegerField(default=0)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(default='无性', max_length=2)),
                ('pet_picture', models.ImageField(default=None, height_field=144, upload_to='../static/pet/', width_field=144)),
                ('birthday', models.DateField(default=None)),
                ('update_time', models.DateField(default=None)),
                ('description', models.TextField(default='我是主人的小棉袄')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('petname', models.CharField(max_length=32)),
                ('position_name', models.CharField(max_length=32)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('position_picture', models.ImageField(default=None, upload_to='../static/position/')),
                ('time', models.DateField(default=None)),
                ('notes', models.TextField(default='到此一游')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='description',
            field=models.TextField(default='宅呀宅呀宅呀宅～～～'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=None, max_length=75),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='其他', max_length=2),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='position',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default=None, height_field=144, upload_to='../static/user/', width_field=144),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateField(default=None),
        ),
    ]
